---
- hosts: localhost

  vars_files:
    - default.config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: dotfiles
      tags: ['dotfiles']
    - role: languages
      tags: ['languages']
    - role: doom_emacs
      tags: ['emacs']
    - role: geerlingguy.mac.dock
      tags: ['dock']
